### ISSUE TITLE
exportKey fails since upgrading to v1.1.4

### ISSUE THREAD

**Issue by gnarea** [PeculiarVentures/webcrypto#23]
I upgraded from 1.1.3 to 1.1.4, and a series of tests have started to fail. All of them fail when using `exportKey`. For example:

```
    Error: Cannot get CryptoKey from secure storage

      at getCryptoKey (node_modules/@relaycorp/relaynet-core/node_modules/@peculiar/webcrypto/build/webcrypto.js:91:15)
      at RsaPssProvider.checkCryptoKey (node_modules/@relaycorp/relaynet-core/node_modules/@peculiar/webcrypto/build/webcrypto.js:1044:29)
      at RsaPssProvider.checkExportKey (node_modules/webcrypto-core/build/webcrypto-core.js:207:14)
      at RsaPssProvider.exportKey (node_modules/webcrypto-core/build/webcrypto-core.js:202:29)
      at SubtleCrypto.exportKey (node_modules/webcrypto-core/build/webcrypto-core.js:838:39)
      at CryptoEngine.exportKey (node_modules/pkijs/src/CryptoEngine.js:604:30)
      at Object.derSerializePublicKey (node_modules/@relaycorp/relaynet-core/src/lib/crypto_wrappers/keys.ts:76:43)
      at PoWebClient.preRegisterNode (src/lib/PoWebClient.ts:123:43)
      at Object.<anonymous> (src/lib/PoWebClient.spec.ts:223:20)
```

Having seeing the changes between the two releases (https://github.com/PeculiarVentures/webcrypto/compare/v1.1.3..v1.1.4), I thought the culprit could've been the upgrade of webcrypto-core, but I couldn't see any change in it that could lead to this behaviour (https://github.com/PeculiarVentures/webcrypto-core/compare/v1.1.6..v1.1.8).

**Comment by microshine** [comment]
@gnarea Looks like your project uses multiple webcrypto modules. As I can see from your exception message you've exception from `node_modules/@relaycorp/relaynet-core/node_modules/@peculiar/webcrypto`. Could you get a list of webcrypto modules for your project?

```
npm list @peculiar/webcrypto
```

Also, you can try to fix it by running

```
npm dedupe
```

**Comment by gnarea** [comment]
Thanks for looking into this @microshine! And good spot -- That was the problem!
