### ISSUE TITLE
ArrayBuffer type error on Jest in ESM mode

### ISSUE THREAD

**Issue by ai** [PeculiarVentures/webcrypto#24]
I use Jest and TS with ESM mode:

```json
  "jest": {
    "preset": "ts-jest/presets/default-esm",
    "globals": {
      "ts-jest": {
        "useESM": true
      }
    },
    "testEnvironment": "jsdom"
  }
```

```sh
node --experimental-vm-modules node_modules/.bin/jest
```

After switching to ESM I start to have `ArrayBuffer` error:

```
    TypeError: The provided value is not of type '(ArrayBuffer or ArrayBufferView)'

      52 |   let key
      53 |   async function getKey () {
    > 54 |     key = await crypto.subtle.importKey(
         |                               ^
      55 |       'raw',
      56 |       await sha256(secret),
      57 |       { name: 'AES-GCM' },

      at Function.toUint8Array (node_modules/pvtsutils/build/index.js:29:17)
      at Function.toArrayBuffer (node_modules/pvtsutils/build/index.js:13:28)
      at SubtleCrypto.importKey (node_modules/webcrypto-core/build/webcrypto-core.js:847:66)
      at getKey (encrypt-actions/index.js:54:31)
      at outMap (encrypt-actions/index.js:69:23)
      at syncMappedEvent (node_modules/@logux/core/base-node/index.js:37:21)
```

Sources:

```js
function sha256 (string) {
  return crypto.subtle.digest('SHA-256', new TextEncoder().encode(string))
}

let key
async function getKey () {
  key = await crypto.subtle.importKey(
    'raw',
    await sha256(secret),
    { name: 'AES-GCM' },
    false,
    ['encrypt', 'decrypt']
  )
  return key
}
```

Seems like switching to ESM created two `ArrayBuffer` instances and `data instanceof ArrayBuffer` start to return `false`.

Will it be more stable to now using `instanceof`?

```js
Object.prototype.toString.call(value) === '[object ArrayBuffer]'
```

**Comment by ai** [comment]
I made PR https://github.com/PeculiarVentures/pvtsutils/pull/4
